// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk1eJUdEKy8sRN_vAbMPNtovPWkFi7A5s',
    appId: '1:98676751264:web:5641f5b70d8a3a920982c5',
    messagingSenderId: '98676751264',
    projectId: 'pokedexghozi',
    authDomain: 'pokedexghozi.firebaseapp.com',
    storageBucket: 'pokedexghozi.appspot.com',
    measurementId: 'G-6JW1DW50L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXI9I7RWK9i61r69jea-DjPoPK349rUV0',
    appId: '1:98676751264:android:6f6d4d1da3ff048b0982c5',
    messagingSenderId: '98676751264',
    projectId: 'pokedexghozi',
    storageBucket: 'pokedexghozi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuZis-Awnjl6QirnHTOYO6cA8cbPAroy4',
    appId: '1:98676751264:ios:4cdfd6bb95e099a80982c5',
    messagingSenderId: '98676751264',
    projectId: 'pokedexghozi',
    storageBucket: 'pokedexghozi.appspot.com',
    iosClientId: '98676751264-d755hbqlqn2fk4rqpe353a7o2f71sl5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuZis-Awnjl6QirnHTOYO6cA8cbPAroy4',
    appId: '1:98676751264:ios:4cdfd6bb95e099a80982c5',
    messagingSenderId: '98676751264',
    projectId: 'pokedexghozi',
    storageBucket: 'pokedexghozi.appspot.com',
    iosClientId: '98676751264-d755hbqlqn2fk4rqpe353a7o2f71sl5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokedexapp',
  );
}
